package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"os"

	curr "github.com/vladimirvivien/go-networking/currency/lib"
)

var (
	currencies = curr.Load("../data.csv")
)

// This program implements a simple currency lookup service
// over TCP or Unix Data Socket. It loads ISO currency
// information using package curr (see above) and uses a simple
// JSON-encode text-based protocol to exchange data with a client.
//
// Clients send currency search requests as JSON objects
// as {"Get":"<currency name,code,or country"}. The request data is
// then unmarshalled to Go type curr.CurrencyRequest using
// the encoding/json package.
//
// The request is then used to search the list of
// currencies. The search result, a []curr.Currency, is marshalled
// as JSON array of objects and sent to the client.
//
// Focus:
// This version of the program introduces the notion of error handling
// when streaming data.  It unpacks the error generated by the JSON
// encoder to distinguish different types of errors and handle them
// accordingly (see code comments).
//
// Testing:
// Netcat can be used for rudimentary testing.  However, use clientjsonX
// programs functional tests.
//
// Usage: server [options]
// options:
//   -e host endpoint, default ":4040"
//   -n network protocol [tcp,unix], default "tcp"
func main() {
	// setup flags
	var addr string
	var network string
	flag.StringVar(&addr, "e", ":4040", "service endpoint [ip addr or socket path]")
	flag.StringVar(&network, "n", "tcp", "network protocol [tcp,unix]")
	flag.Parse()

	// validate supported network protocols
	switch network {
	case "tcp", "tcp4", "tcp6", "unix":
	default:
		fmt.Println("unsupported network protocol")
		os.Exit(1)
	}

	// create a listener for provided network and host address
	ln, err := net.Listen(network, addr)
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
	defer ln.Close()
	log.Println("**** Global Currency Service ***")
	log.Printf("Service started: (%s) %s\n", network, addr)

	// connection loop
	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Println(err)
			conn.Close()
			continue
		}
		log.Println("Connected to ", conn.RemoteAddr())
		go handleConnection(conn)
	}
}

// handle client connection
func handleConnection(conn net.Conn) {
	defer func() {
		if err := conn.Close(); err != nil {
			log.Println("error closing connection:", err)
		}
	}()

	// command-loop
	for {
		dec := json.NewDecoder(conn)
		// Next decode the incoming data into Go value curr.CurrencyRequest
		var req curr.CurrencyRequest
		if err := dec.Decode(&req); err != nil {
			// json.Decode() could return decoding err,
			// io err, or networking err.  This makes error handling
			// a little more complex.

			// handle error based on error type
			switch err := err.(type) {
			//network error: disconnect
			case net.Error:
				// dont continue, break connection
				fmt.Println("network error:", err)
				return

			//other errors: send error info to client, then continue
			default:
				if err == io.EOF {
					fmt.Println("closing connection:", err)
					return
				}
				// encode curr.CurrencyError to send to client
				enc := json.NewEncoder(conn)
				if encerr := enc.Encode(&curr.CurrencyError{Error: err.Error()}); encerr != nil {
					// if failure at this point, drop connection
					fmt.Println("failed error encoding:", encerr)
					return
				}
				continue
			}
		}

		// search currencies, result is []curr.Currency
		result := curr.Find(currencies, req.Get)

		// encode result to JSON array
		enc := json.NewEncoder(conn)
		if err := enc.Encode(&result); err != nil {
			switch err := err.(type) {
			case net.Error:
				fmt.Println("failed to send response:", err)
				return
			default:
				if encerr := enc.Encode(&curr.CurrencyError{Error: err.Error()}); encerr != nil {
					fmt.Println("failed to send error:", encerr)
					return
				}
				continue
			}
		}
	}
}
